image: registry.k8s.work.iqvia.com/cio-centos-base

stages:
  - buildImage

Build Gangway Image:
  stage: buildImage
  image: registry.k8s.work.iqvia.com/cio-docker-base
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_PUSH_REGISTRY_URL
  script:
    - apk add --no-cache make build-base
    - make cio-push COMMIT_SHA=$CI_COMMIT_SHORT_SHA COMMIT_REF_NAME=$CI_COMMIT_REF_NAME
